### ISSUE TITLE
Conference selection is "broken" after updating from previous version

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#113]
When I select Devoxx Belgium from the new home page on an Android device, the actual event is not selected.  As a result no speakers are shown and the actual event title shows only "Devoxx" instead of "Devoxx BE" !! 

This is not the case in the iOS version.

![image](https://user-images.githubusercontent.com/179457/45410254-8c86bc00-b671-11e8-8b49-544f892841bc.png)

**Comment by tiainen** [comment]
When downloading API data (like conferences, sessions, speakers, etc), the application will also keep a local copy of that data. This is to improve loading times and network usage the next time this data needs to be accessed.

The problem here is that the data structures have changed in the latest version. To fix this, the application must be able to handle the cached data with the previous structure and then discard that data and fetch the new data.

As a workaround, you can first remove the application and then install again.

**Comment by tiainen** [comment]
There seems to be another issue that causes this bug, which is related to issue #112. The conference details are loaded when a conference is selected from the start-up screen. This is done by invoking a remote function to the new devoxx backend. When that call fails, no furhter conference information can be loaded.

Some things that can be done:
- add visual feedback that the conference details are loaded, by navigating to an intermediate view instead of directly to the sessions overview
- handle the case where the invocation to the remote function fails: add an option to either reload or navigate back to the conference selector screen
- use a cached json file (for each conference) as suggested in #112

**Comment by abhinayagarwal** [comment]
We have the following files in private storage:

* userInfo (stores user login info)
* settings.properties (stores various information including conference no, sponsor details, etc)
* *.cache
* *.info
* reload (for silent push notification)
* MediaClient images

The important files are userInfo and settings.properties. The advantage of keeping these files is: 

* user doesn't have to re-login
* user doesn't have to skip the video

I have been wondering if its ok to only delete the cache and info files? This will leave the MediaClient images, reload, userInfo, settings.properties. All of these images should not have any side-effect on the new version.

Or, should we delete everything except userInfo and settings.properties?

I cannot test the above to be surem because all the RF in GCL has been changed.
