### ISSUE TITLE
Automatically trigger rate dialog at the end of the conference

### ISSUE THREAD

**Issue by erwin1** [devoxx/MyDevoxxGluon#159]
Instead of awaiting a silent push notication as described in #85 the app should trigger the rate dialog at the end of the conference.

**Comment by abhinayagarwal** [comment]
Hi @stephanj,

What should be a good time to schedule the rate dialog?

There is a high probability that no one will open the app once the conference is over. Therefore, may be we should trigger it at the start of last day? Or at some point of time when we know that people have used the used the app (and are ready to review it) but would also open the app in future (so that they can see the dialog and leave a review)

**Comment by stephanj** [comment]
Start of the last day is fine by me, thanks!
