### ISSUE TITLE
Favs are not restored when restarting app

### ISSUE THREAD

**Issue by stephanj** [devoxx/MyDevoxxGluon#192]
I can favourite talks in the mobile app when authenticated, however when I restart the mobile app the favs are gone. (BTW I'm still authenticated in the mobile app)  

When I check the web version of the schedule, the favs are still there.

**Comment by stephanj** [comment]
It looks like the app still knows about my favs because I'm stilling getting notifications BUT they're not shown in the schedule.

![image](https://user-images.githubusercontent.com/179457/47652121-65367080-db85-11e8-82fb-4863c95a9bd3.png)

**Comment by stephanj** [comment]
![image](https://user-images.githubusercontent.com/179457/47652355-f9083c80-db85-11e8-918e-06f327e80e03.png)

**Comment by erwin1** [comment]
This problem is confirmed to occur under these circumstances:
- user had the app installed last year
- user is still logged in (cfp uuid is stored in app settings)
- user did not logout/login this year

In that case, the app will still use last year's cfp user id to save favourites, which obviously doesn't exist at the backend anymore. So when the favourites are synced again, they are overwritten with whatever is available at the backend (usually none, unless the user scheduled on the web as well)

The issue is fixed in version 3.4.3. Users of earlier versions should use one of the workaround:
- logout and log back in before scheduling anything
- switch to a different conference and then switch back to Devoxx Belgium
